apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfixadmin
  labels:
    app: postfixadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfixadmin
  template:
    metadata:
      labels:
        app: postfixadmin
    spec:
      containers:
        - name: postfixadmin
          image: "docker.io/postfixadmin:3.3.10"
          ports:
            - name: http
              containerPort: 8087
          env:
            - name: POSTFIXADMIN_DB_TYPE
              value: mysql
            - name: POSTFIXADMIN_DB_HOST
              value: mysql-host
            - name: POSTFIXADMIN_DB_USER
              value: postfixuser
            - name: POSTFIXADMIN_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-db-password
                  key: db-password
          volumeMounts:
            - name: postfixadmin-data
              mountPath: /var/www/html
      volumes:
        - name: postfixadmin-data
          persistentVolumeClaim:
            claimName: postfixadmin-pvc
